### PR TITLE
aria-label to 2 form controls

### PR DESCRIPTION
**Pull request by estelle**
aria-label=&quot;select a color&quot;

### CODE REVIEW

**Comment by una** [comment]
Would love to get this in once the `html.html` is edited

**Comment by jpdevries** [comment]
ARIA has poor browser support ([no browser fully supports it](http://caniuse.com/#feat=wai-aria)). What about using a `<label>` and accessibly (visually) hiding it if needed?

**Comment by robdodson** [comment]
I think aria-label has good support across screen readers but +1 to not using aria if you can avoid it and sticking with the invisible label approach. Here's a good article on how to do it: http://webaim.org/techniques/css/invisiblecontent/ You've got to be careful because completely removing the label (like setting it to display: none or width: 0 height: 0) will cause screen readers to ignore it. That article recommends doing something like:

```
.hidden 
{position:absolute;
left:-10000px;
top:auto;
width:1px;
height:1px;}
```

The article I linked to recommends also setting overflow: hidden but I'd advise against that as recently it was reported to me that this was causing screen readers to ignore the element.

**Comment by jpdevries** [comment]
I do something similar and also set `position:relative` on the parent. Otherwise VoiceOver (SwitchControl) on iOS will draw really weird focus outlines that go way off the screen.

``` css
.visually-hidden { /*https://developer.yahoo.com/blogs/ydn/clip-hidden-content-better-accessibility-53456.html*/
    position: absolute !important;
    clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
    clip: rect(1px, 1px, 1px, 1px);
    padding:0 !important;
    border:0 !important;
    height: 1px !important;
    width: 1px !important;
    overflow: hidden;
} 
body:hover .visually-hidden a, body:hover .visually-hidden input, body:hover .visually-hidden button { display: none !important; } 
```

http://a11yproject.com/posts/how-to-hide-content/

**Comment by una** [comment]
Closing due to inactivity, will be addressed

**Pull request closed without merging**
