### PR TITLE
Fix/image slider

### PR DESCRIPTION
**Pull request by shadeed**
A fix for #13.  Replaced `left` with `transform` for a less janky effect.

Updated pen:
http://codepen.io/shadeed/pen/LRmAyp?editors=0100

### CODE REVIEW

**Comment by una** [comment]
These are great updates (also the other PR)! I'll pull this down later today and take a closer look :D Thank you!

**Comment by shadeed** [comment]
@una you are welcome :) 

A quick note: I worked on other changes in PR #11 and accidentally pushed them with this PR.. So we might need to close #11 and keep this one. (Sorry 🙈)

**Comment by una** [comment]
Going to merge this and close the other one, then update the Codepens--is it cool if I update them on my end to keep consistency?

**Comment by shadeed** [comment]
@una sure thing :)

**Pull request merged**
