### PR TITLE
Modal dialog accessibility

### PR DESCRIPTION
**Pull request by marcysutton**
So my first attempt at a component accessibility improvement is for the modal dialog. I wrote a comment warning about the limitations, since it is not a real-world solution. But I think it captures the spirit of the project by showing something cool with CSS and focus management. I changed the DIV to a native dialog element but the API for opening it requires JavaScript. Waah waah....

My first example showed the dialog by focusing on it with an internal link, but it was more limited. The latest version uses `:target` so you can actually tab to the child items inside the dialog. But it doesn't trap focus, so it's still limited. If HTML `inert` was a thing, you could trap focus more easily. But it would still require JS to toggle it on the background content. 

Note: it still needs JS to bind the escape key to close the dialog, an important convention for interactive overlays.

Here's the Codepen: http://codepen.io/marcysutton/pen/mAKrxb

If you're curious about hiding things with CSS and how they impact the keyboard, this video might come in handy: https://egghead.io/lessons/html-5-visible-vs-hidden

### CODE REVIEW

**Comment by marcysutton** [comment]
Gah, i tried to isolate my commits between PRs but they ended up here. oh well.

**Comment by robdodson** [comment]
I'm obligated to give a shout out to the [inert polyfill](https://github.com/WICG/inert) here :D

**Comment by marcysutton** [comment]
I wonder if excluding index.html in .gitignore would help minimize conflicts? Since it's generated and all...

**Comment by una** [comment]
Unforuntately the site is served on gh-pages and requires `index.html` to be visible

**Comment by opattison** [comment]
@una One possibility for solving that issue is to keep building the site on the `gh-pages` branch (keeping files like `index.html` tracked in Git) but on `master` making sure any`.html` files generated by your build process are ignored by Git. Then you could have contributors PR to the main branch (`master`). Merge `master` into `gh-pages` and rebuild when you are ready to re-publish after a successful PR.

Given what I’ve seen about your dev setup, it looks like you are using a custom build on a local machine, which is definitely a good reason to publish flat HTML files to `gh-pages`. But I hope that might save you a conflict headache if that workflow works for you!

**Comment by marcysutton** [comment]
@una I fixed the conflict!

**Comment by una** [comment]
Hi! Thanks, this is great 😄 if you can remove `index.html` I'll take care of the merge without a conflict

**Comment by marcysutton** [comment]
@una do you still need me to do anything? Looks like the merge went ok?

**Pull request merged**
